"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { ArrowLeft, ArrowUpRight, Bell, Check, ChefHat, CircleAlert, CreditCard, Leaf, Menu, Plus, ScanLine, ShieldCheck, Sparkles, Table2, UsersRound, X } from "lucide-react";
import { inventory, menu, orders, queue, restaurant } from "@/lib/demo-data";

type Page = "guest" | "queue" | "service" | "kitchen" | "inventory" | "safety" | "analytics" | "billing" | "table";

const links: Array<{ href: string; label: string; icon: typeof ScanLine }> = [
  { href: "/guest", label: "Guest menu", icon: ScanLine }, { href: "/queue", label: "Waitlist", icon: UsersRound },
  { href: "/service", label: "Service floor", icon: Table2 }, { href: "/kitchen", label: "Kitchen line", icon: ChefHat },
  { href: "/inventory", label: "Pantry", icon: Leaf }, { href: "/safety", label: "SafePlate", icon: ShieldCheck },
  { href: "/analytics", label: "Signals", icon: Sparkles }, { href: "/billing", label: "Billing", icon: CreditCard },
];

const meta: Record<Page, { lens: string; title: string; description: string }> = {
  guest: { lens: "Guest lens", title: "Choose with confidence.", description: "Live dishes, honest timing and dietary context that stays with your table." },
  queue: { lens: "Arrival lens", title: "Waiting, made visible.", description: "Every party gets a useful estimate and staff sees the best next table." },
  service: { lens: "Floor lens", title: "Feel the room, not the scramble.", description: "The guest moments that need a person, arranged by urgency." },
  kitchen: { lens: "Kitchen lens", title: "A quieter way to run the line.", description: "Tickets hold their timing, safety context and next action in one place." },
  inventory: { lens: "Pantry lens", title: "See the ingredient ripple.", description: "Stock changes become useful decisions before they become guest disappointments." },
  safety: { lens: "SafePlate lens", title: "Context should never get lost.", description: "A visible safety relay from the guest's choice to the final handoff." },
  analytics: { lens: "Signal lens", title: "Patterns that tell you what to do.", description: "Operational intelligence with an action attached to every insight." },
  billing: { lens: "Close lens", title: "Close the table with grace.", description: "Orders, discounts and payment status stay clear until the final receipt." },
  table: { lens: "Table session", title: "Welcome to table 08.", description: "Your menu, dietary notes, order and service requests live right here." },
};

export function Workspace({ page }: { page: Page }) {
  const [cart, setCart] = useState<string[]>([]);
  const [constraints, setConstraints] = useState<string[]>(["Gluten"]);
  const [drawer, setDrawer] = useState(false);
  const content = page === "guest" || page === "table" ? <Guest cart={cart} setCart={setCart} constraints={constraints} setConstraints={setConstraints} table={page === "table"} /> : page === "queue" ? <Queue /> : page === "service" ? <Service /> : page === "kitchen" ? <Kitchen /> : page === "inventory" ? <Inventory /> : page === "safety" ? <Safety /> : page === "analytics" ? <Analytics /> : <Billing />;
  return <div className="constellation"><header className="constellation-top"><Link href="/" className="pulse-logo"><span>D</span><b>DINE<br />AI</b></Link><nav className={drawer ? "nav-open" : ""}>{links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={page === href.slice(1) || (page === "table" && href === "/guest") ? "current" : ""}><Icon size={16} />{label}</Link>)}</nav><div className="top-tools"><button onClick={() => toast.info("3 operational updates") } aria-label="Notifications"><Bell size={18} /><i>3</i></button><button className="nav-toggle" onClick={() => setDrawer(!drawer)} aria-label="Toggle navigation">{drawer ? <X size={19} /> : <Menu size={19} />}</button></div></header><main className="constellation-main"><div className="lens"><p>{meta[page].lens}</p><Link href="/" aria-label="Back to all workspaces"><ArrowLeft size={16} /></Link></div><section className="workspace-heading"><div><h1>{meta[page].title}</h1><p>{meta[page].description}</p></div><div className="service-beacon"><i /><span>Live at {restaurant.name}</span></div></section>{content}</main></div>;
}

function Guest({ cart, setCart, constraints, setConstraints, table }: { cart: string[]; setCart: (items: string[]) => void; constraints: string[]; setConstraints: (items: string[]) => void; table: boolean }) {
  const total = useMemo(() => cart.reduce((sum, id) => sum + (menu.find((item) => item.id === id)?.priceCents ?? 0), 0), [cart]);
  return <><section className="guest-signal"><div className="signal-copy"><span>{table ? "TABLE 08 / YOUR LIVE SESSION" : "TANDOOR BISTRO IS SERVING NOW"}</span><h2>{table ? "Your table is already in rhythm." : "A menu that knows the moment."}</h2><p>{table ? "Two guests - Server Sam is nearby - Your order can carry every preference." : `${restaurant.activeTables} tables are in motion. ${restaurant.totalTables - restaurant.activeTables} are open right now.`}</p><button onClick={() => toast.success(table ? "Service request sent" : "You are #3 in line - 18 minutes")}>{table ? "Request service" : "Join the waitlist"}<ArrowUpRight size={17} /></button></div><div className="signal-orbit"><b>18<span>min</span></b><small>Current wait</small><i className="ring one" /><i className="ring two" /><em>*</em></div></section><section className="preference-strip"><div><p>YOUR PREFERENCES</p><h3>We will keep these visible through every handoff.</h3></div><div>{["Soy", "Peanut", "Dairy", "Gluten", "Vegan"].map((item) => <button key={item} className={constraints.includes(item) ? "chosen" : ""} onClick={() => setConstraints(constraints.includes(item) ? constraints.filter((x) => x !== item) : [...constraints, item])}>{constraints.includes(item) && <Check size={13} />}{item}</button>)}</div></section><section className="dish-field">{menu.map((dish, index) => { const conflict = constraints.some((constraint) => dish.tags.includes(constraint)); const disabled = conflict; return <article className={`dish-cell cell-${index + 1}`} key={dish.id}><div className="dish-visual" style={{ backgroundImage: `url(${dish.image})`, backgroundSize: 'cover', backgroundPosition: 'center' }}><span>{dish.prepMinutes} min</span></div><div className="dish-copy"><div><p>{dish.availability === "AVAILABLE" ? "* Available now" : dish.availability === "REVIEW" ? "! Ask before ordering" : "~ Can modify"}</p><h3>{dish.name}</h3><small>{dish.description}</small></div><div className="dish-footer"><b>₹{(dish.priceCents / 100).toFixed(2)}</b><button disabled={disabled} onClick={() => { setCart([...cart, dish.id]); toast.success(`${dish.name} added`); }}><Plus size={16} />{disabled ? "Review" : "Add"}</button></div></div></article>; })}</section>{cart.length > 0 && <aside className="order-orb"><div><span>{cart.length} selection{cart.length > 1 ? "s" : ""}</span><b>₹{(total / 100).toFixed(2)}</b><small>Dietary context checked at checkout</small></div><button onClick={() => { setCart([]); toast.success("Order RP-1049 is with the kitchen"); }}>Send to kitchen <ArrowUpRight size={17} /></button></aside>}</>;
}

function Queue() { return <section className="arrival-layout"><div className="arrival-core"><p>YOUR CURRENT ESTIMATE</p><strong>18<span>min</span></strong><h2>We are setting the right table free.</h2><div className="arrival-math"><span><b>02</b> parties ahead</span><i>+</i><span><b>04</b> fitting tables</span><i>=</i><span><b>18m</b> estimate</span></div></div><div className="queue-list">{queue.map((entry) => <article key={entry.position}><span>{String(entry.position).padStart(2, "0")}</span><div><b>{entry.name}</b><small>{entry.party} guests - {entry.note}</small></div><strong>{entry.estimate}m</strong><button onClick={() => toast.success(`${entry.name} marked ready to seat`)}>Seat</button></article>)}</div></section>; }

function Service() { return <section className="floor-layout"><div className="floor-grid">{Array.from({ length: 14 }, (_, index) => <button key={index} className={index === 7 ? "urgent" : index < 10 ? "seated" : "free"} onClick={() => toast.info(`Table ${String(index + 1).padStart(2, "0")} selected`)}><b>{String(index + 1).padStart(2, "0")}</b><span>{index === 7 ? "safety" : index < 10 ? `${[2, 3, 4][index % 3]} guests` : "open"}</span></button>)}</div><div className="service-trail"><p>THE NEXT THREE MOMENTS</p>{[["08", "Resolve gluten substitution", "Safety-critical"], ["11", "Deliver ready dishes", "1 min ago"], ["04", "Bring water", "2 min ago"]].map(([table, title, note]) => <button key={title} onClick={() => toast.success(`${title} assigned to you`)}><span>T{table}</span><b>{title}<small>{note}</small></b><ArrowUpRight size={16} /></button>)}</div></section>; }

function Kitchen() { return <section className="line-board">{orders.map((order) => <article className={order.status === "REQUIRES_ATTENTION" ? "heat-card alert" : "heat-card"} key={order.id}><header><span>{order.table}</span><b>{order.id}</b><em>{order.elapsed}m</em></header><div><p>{order.status.replaceAll("_", " ")}</p><h3>{order.guest}</h3><small>{order.items.join(" - ")}</small>{order.safety && <aside><ShieldCheck size={16} /><span><b>SafePlate pause</b>{order.safety}</span></aside>}</div><footer><button onClick={() => toast.success(`${order.id} started`)}>Start</button><button onClick={() => toast.success(`${order.id} ready for service`)}>Ready</button></footer></article>)}</section>; }

function Inventory() { return <section className="pantry-map"><div className="ingredient-axis">{inventory.map((item) => <article key={item.name}><span>{item.name.charAt(0)}</span><div><b>{item.name}</b><small>{item.remaining} {item.unit} remaining</small></div><div className="supply-line"><i style={{ width: `${item.percent}%` }} /></div><em className={item.state.toLowerCase()}>{item.state}</em><button onClick={() => toast.info(`${item.name} adjustment opened`)}><ArrowUpRight size={16} /></button></article>)}</div><aside><Leaf size={26} /><p>LIVE IMPACT</p><h2>Ingredient changes ripple through menu and orders automatically.</h2><span>Chicken is low, 3 menu items watched, 1 active order monitored</span></aside></section>; }

function Safety() { return <section className="safety-circuit"><div className="relay-card"><p>ORDER RP-1048 - TABLE 08</p><h2>The recipe changed. The promise must stay visible.</h2><div className="conflict"><CircleAlert size={19} /><span><b>Gluten conflict detected</b>The new recipe is not compatible with Maya's constraint.</span></div><button onClick={() => toast.success("Kitchen acknowledgement recorded")}>Acknowledge in kitchen <ShieldCheck size={17} /></button></div><div className="relay-path">{[["01", "Guest", "Gluten saved with order", true], ["02", "Service", "Acknowledged by Sam", true], ["03", "Kitchen", "Waiting for confirmation", false], ["04", "Delivery", "Unlocks after prep", false]].map(([number, title, detail, done]) => <article className={done ? "done" : ""} key={title as string}><span>{done ? <Check size={15} /> : number}</span><b>{title}<small>{detail}</small></b></article>)}</div><div className="alternative-burst"><p>SAFE ALTERNATIVES</p>{["Butter Chicken", "Malai Kofta", "Baingan Bharta"].map((name) => <button onClick={() => toast.success(`${name} sent to Maya for review`)} key={name}>{name}<small>Compatible and available</small><ArrowUpRight size={15} /></button>)}</div></section>; }

function Analytics() { return <section className="signal-field"><article className="signal-card main"><Sparkles size={24} /><p>THE STRONGEST SIGNAL</p><h2>The hearth is about to create a four-minute drag between 7:30 and 8:00pm.</h2><span>Move one service teammate to expediting and show faster compatible alternatives first.</span><button onClick={() => toast.success("Signal marked as reviewed")}>Mark reviewed <Check size={15} /></button></article><article className="signal-card"><p>TABLE TURN</p><h3>72 min</h3><b>6 min faster</b></article><article className="signal-card"><p>SAFEPLATE</p><h3>100%</h3><b>All checks complete</b></article><article className="signal-card"><p>STOCKOUTS AVOIDED</p><h3>08</h3><b>+3 this week</b></article></section>; }

function Billing() { return <section className="close-layout"><div className="receipt"><p>READY TO CLOSE - TABLE 11</p><h2>Ananya Patel</h2><span>Baingan Bharta <b>₹145.00</b></span><span>Kadhai Paneer <b>₹220.00</b></span><span>CGST/SGST <b>₹32.85</b></span><footer><b>Total</b><strong>₹397.85</strong></footer><button onClick={() => toast.success("Payment recorded. Receipt RP-1046 is ready.")}>Mark paid <CreditCard size={16} /></button></div><div className="receipt-stream"><p>RECENT RECEIPTS</p>{["RP-1045 - ₹640.00", "RP-1044 - ₹480.00", "RP-1043 - ₹350.00"].map((receipt) => <button key={receipt} onClick={() => toast.info(`${receipt} opened`)}><Check size={15} />{receipt}<ArrowUpRight size={15} /></button>)}</div></section>; }
